default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username is 'iou'
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  database: iou_development

test:
  <<: *default
  database: iou_test

production:
  <<: *default
  database: iou_production
  password: <%= Rails.application.credentials.database[:password_prod] %>
